repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
        exclude: tests
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      # https://stackoverflow.com/a/71662957
      - id: mypy
        name: mypy
        files: ^app
        args: ["--config-file", "pyproject.toml", "--show-traceback"]
        
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        name: ruff
        files: ^app/
        args: ["--fix"]
      - id: ruff-format
        name: ruff-format
        files: ^app
